/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "protocol/gen-cpp2/calc_types.h"

namespace fbthrift { namespace calc { namespace cpp2 {

struct calc_constants {

};

}}} // fbthrift::calc::cpp2
