/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_metadata_h.h>
#include "protocol/gen-cpp2/calc_types.h"

namespace fbthrift {
namespace calc {
namespace cpp2 {
class CalculatorServiceSvIf;
}}} // namespace fbthrift::calc::cpp2

namespace apache {
namespace thrift {
namespace detail {
namespace md {
using ThriftMetadata = ::apache::thrift::metadata::ThriftMetadata;
using ThriftServiceContext = ::apache::thrift::metadata::ThriftServiceContext;
using ThriftService = ::apache::thrift::metadata::ThriftService;

template <>
class StructMetadata<::fbthrift::calc::cpp2::AddRequest> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class StructMetadata<::fbthrift::calc::cpp2::AddResponse> {
 public:
  static void gen(ThriftMetadata& metadata);
};
template <>
class ServiceMetadata<::fbthrift::calc::cpp2::CalculatorServiceSvIf> {
 public:
  static void gen(ThriftMetadata& metadata, ThriftServiceContext& context);
 private:
  static void gen_add(ThriftMetadata& metadata, ThriftService& context);
};
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
