/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "protocol/gen-cpp2/calc_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace fbthrift { namespace calc { namespace cpp2 {

}}} // fbthrift::calc::cpp2
