/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "protocol/gen-cpp2/CalculatorService.h"
#include "protocol/gen-cpp2/CalculatorService.tcc"

namespace fbthrift { namespace calc { namespace cpp2 {
}}} // fbthrift::calc::cpp2
