/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "protocol/gen-cpp2/CalculatorServiceAsyncClient.h"

#include <thrift/lib/cpp2/gen/client_cpp.h>

namespace fbthrift { namespace calc { namespace cpp2 {
typedef apache::thrift::ThriftPresult<false, apache::thrift::FieldData<1, apache::thrift::protocol::T_STRUCT,  ::fbthrift::calc::cpp2::AddRequest*>> CalculatorService_add_pargs;
typedef apache::thrift::ThriftPresult<true, apache::thrift::FieldData<0, apache::thrift::protocol::T_STRUCT,  ::fbthrift::calc::cpp2::AddResponse*>> CalculatorService_add_presult;

template <typename Protocol_>
void CalculatorServiceAsyncClient::addT(Protocol_* prot, apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::detail::ac::ClientRequestContext> ctx, apache::thrift::RequestClientCallback::Ptr callback, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  std::shared_ptr<apache::thrift::transport::THeader> header(ctx, &ctx->header);
  CalculatorService_add_pargs args;
  args.get<0>().value = const_cast< ::fbthrift::calc::cpp2::AddRequest*>(&req);
  auto sizer = [&](Protocol_* p) { return args.serializedSizeZC(p); };
  auto writer = [&](Protocol_* p) { args.write(p); };
  apache::thrift::clientSendT<Protocol_>(prot, rpcOptions, std::move(callback), ctx->ctx, std::move(header), channel_.get(), "add", writer, sizer, apache::thrift::RpcKind::SINGLE_REQUEST_SINGLE_RESPONSE);
  ctx->reqContext.setRequestHeader(nullptr);
}



void CalculatorServiceAsyncClient::add(std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  ::apache::thrift::RpcOptions rpcOptions;
  add(rpcOptions, std::move(callback), req);
}

void CalculatorServiceAsyncClient::add(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  auto ctx = std::make_shared<apache::thrift::detail::ac::ClientRequestContext>(
      apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId(),
      rpcOptions.releaseWriteHeaders(),
      this->handlers_,
      this->getServiceName(),
      "CalculatorService.add");
  apache::thrift::RequestCallback::Context callbackContext;
  callbackContext.protocolId =
      apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
  callbackContext.ctx = std::shared_ptr<apache::thrift::ContextStack>(ctx, &ctx->ctx);
  addImpl(rpcOptions, std::move(ctx), apache::thrift::toRequestClientCallbackPtr(std::move(callback), std::move(callbackContext)), req);
}

void CalculatorServiceAsyncClient::addImpl(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::detail::ac::ClientRequestContext> ctx, apache::thrift::RequestClientCallback::Ptr callback, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  switch (apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId()) {
    case apache::thrift::protocol::T_BINARY_PROTOCOL:
    {
      apache::thrift::BinaryProtocolWriter writer;
      addT(&writer, rpcOptions, std::move(ctx), std::move(callback), req);
      break;
    }
    case apache::thrift::protocol::T_COMPACT_PROTOCOL:
    {
      apache::thrift::CompactProtocolWriter writer;
      addT(&writer, rpcOptions, std::move(ctx), std::move(callback), req);
      break;
    }
    default:
    {
      apache::thrift::detail::ac::throw_app_exn("Could not find Protocol");
    }
  }
}

void CalculatorServiceAsyncClient::sync_add( ::fbthrift::calc::cpp2::AddResponse& _return, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  ::apache::thrift::RpcOptions rpcOptions;
  sync_add(rpcOptions, _return, req);
}

void CalculatorServiceAsyncClient::sync_add(apache::thrift::RpcOptions& rpcOptions,  ::fbthrift::calc::cpp2::AddResponse& _return, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  apache::thrift::ClientReceiveState _returnState;
  apache::thrift::ClientSyncCallback<false> callback(&_returnState);
  auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
  auto evb = apache::thrift::GeneratedAsyncClient::getChannel()->getEventBase();
  auto ctx = std::make_shared<apache::thrift::detail::ac::ClientRequestContext>(
      protocolId,
      rpcOptions.releaseWriteHeaders(),
      this->handlers_,
      this->getServiceName(),
      "CalculatorService.add");
  addImpl(rpcOptions, ctx, apache::thrift::RequestClientCallback::Ptr(&callback), req);
  callback.waitUntilDone(evb);
  _returnState.resetProtocolId(protocolId);
  _returnState.resetCtx(std::shared_ptr<apache::thrift::ContextStack>(ctx, &ctx->ctx));
  SCOPE_EXIT {
    if (_returnState.header() && !_returnState.header()->getHeaders().empty()) {
      rpcOptions.setReadHeaders(_returnState.header()->releaseHeaders());
    }
  };
  if (!_returnState.buf()) {
    assert(!!_returnState.exception());
    _returnState.exception().throw_exception();
  }
  return folly::fibers::runInMainContext([&] {
      recv_add(_return, _returnState);
  });
}



folly::Future< ::fbthrift::calc::cpp2::AddResponse> CalculatorServiceAsyncClient::future_add(const  ::fbthrift::calc::cpp2::AddRequest& req) {
  ::apache::thrift::RpcOptions rpcOptions;
  return future_add(rpcOptions, req);
}

folly::SemiFuture< ::fbthrift::calc::cpp2::AddResponse> CalculatorServiceAsyncClient::semifuture_add(const  ::fbthrift::calc::cpp2::AddRequest& req) {
  ::apache::thrift::RpcOptions rpcOptions;
  return semifuture_add(rpcOptions, req);
}

folly::Future< ::fbthrift::calc::cpp2::AddResponse> CalculatorServiceAsyncClient::future_add(apache::thrift::RpcOptions& rpcOptions, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  folly::Promise< ::fbthrift::calc::cpp2::AddResponse> _promise;
  auto _future = _promise.getFuture();
  auto callback = std::make_unique<apache::thrift::FutureCallback< ::fbthrift::calc::cpp2::AddResponse>>(std::move(_promise), recv_wrapped_add, channel_);
  add(rpcOptions, std::move(callback), req);
  return _future;
}

folly::SemiFuture< ::fbthrift::calc::cpp2::AddResponse> CalculatorServiceAsyncClient::semifuture_add(apache::thrift::RpcOptions& rpcOptions, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  auto callbackAndFuture = makeSemiFutureCallback(recv_wrapped_add, channel_);
  auto callback = std::move(callbackAndFuture.first);
  add(rpcOptions, std::move(callback), req);
  return std::move(callbackAndFuture.second);
}

folly::Future<std::pair< ::fbthrift::calc::cpp2::AddResponse, std::unique_ptr<apache::thrift::transport::THeader>>> CalculatorServiceAsyncClient::header_future_add(apache::thrift::RpcOptions& rpcOptions, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  folly::Promise<std::pair< ::fbthrift::calc::cpp2::AddResponse, std::unique_ptr<apache::thrift::transport::THeader>>> _promise;
  auto _future = _promise.getFuture();
  auto callback = std::make_unique<apache::thrift::HeaderFutureCallback< ::fbthrift::calc::cpp2::AddResponse>>(std::move(_promise), recv_wrapped_add, channel_);
  add(rpcOptions, std::move(callback), req);
  return _future;
}

folly::SemiFuture<std::pair< ::fbthrift::calc::cpp2::AddResponse, std::unique_ptr<apache::thrift::transport::THeader>>> CalculatorServiceAsyncClient::header_semifuture_add(apache::thrift::RpcOptions& rpcOptions, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  auto callbackAndFuture = makeHeaderSemiFutureCallback(recv_wrapped_add, channel_);
  auto callback = std::move(callbackAndFuture.first);
  add(rpcOptions, std::move(callback), req);
  return std::move(callbackAndFuture.second);
}
void CalculatorServiceAsyncClient::add(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const  ::fbthrift::calc::cpp2::AddRequest& req) {
  add(std::make_unique<apache::thrift::FunctionReplyCallback>(std::move(callback)), req);
}

folly::exception_wrapper CalculatorServiceAsyncClient::recv_wrapped_add( ::fbthrift::calc::cpp2::AddResponse& _return, ::apache::thrift::ClientReceiveState& state) {
  if (state.isException()) {
    return std::move(state.exception());
  }
  if (!state.buf()) {
    return folly::make_exception_wrapper<apache::thrift::TApplicationException>("recv_ called without result");
  }

  using result = CalculatorService_add_presult;
  constexpr auto const fname = "add";
  switch (state.protocolId()) {
    case apache::thrift::protocol::T_BINARY_PROTOCOL:
    {
      apache::thrift::BinaryProtocolReader reader;
      return apache::thrift::detail::ac::recv_wrapped<result>(
          fname, &reader, state, _return);
    }
    case apache::thrift::protocol::T_COMPACT_PROTOCOL:
    {
      apache::thrift::CompactProtocolReader reader;
      return apache::thrift::detail::ac::recv_wrapped<result>(
          fname, &reader, state, _return);
    }
    default:
    {
    }
  }
  return folly::make_exception_wrapper<apache::thrift::TApplicationException>("Could not find Protocol");
}

void CalculatorServiceAsyncClient::recv_add( ::fbthrift::calc::cpp2::AddResponse& _return, ::apache::thrift::ClientReceiveState& state) {
  auto ew = recv_wrapped_add(_return, state);
  if (ew) {
    ew.throw_exception();
  }
}

void CalculatorServiceAsyncClient::recv_instance_add( ::fbthrift::calc::cpp2::AddResponse& _return, ::apache::thrift::ClientReceiveState& state) {
  return recv_add(_return, state);
}

folly::exception_wrapper CalculatorServiceAsyncClient::recv_instance_wrapped_add( ::fbthrift::calc::cpp2::AddResponse& _return, ::apache::thrift::ClientReceiveState& state) {
  return recv_wrapped_add(_return, state);
}

}}} // fbthrift::calc::cpp2
